export default {
  input: 'src/index.js',
  output: [
    {
      intro: '/* This file is auto generated by rollup.\nUse `npm run build` to create new CommonJS bundle. */',
      exports: 'named',
      // note: this bundle needs the wrapper `./dist/index.cjs` to properly export defaults
      file: './dist/bundle.cjs',
      format: 'cjs',
    },
    {
      intro: '/* This file is auto generated by rollup.\nUse `npm run build` to create new ES Module bundle. */',
      file: './dist/index.mjs',
      format: 'es',
    },
  ],
};
